### PR TITLE
color of collapse component goes out fix

### LINKED ISSUE #269: Color of the Collapse component goes out of border
**Describe the bug**
To represent each K8s resource deployed for a Module we are using ant design [Collapse.Panel](https://github.com/cyclops-ui/cyclops/blob/ec164f960cde9a37212200e6f21b9ff592adb448/cyclops-ui/src/components/pages/ModuleDetails.tsx#L476). The issue is that the color is going out of the component on the upper corner and should be contained as it is on the bottom corners.

The corner where the color goes outside the component is highlighted with a red circle on the picture below
Screenshot 2024-05-16 at 13 45 25

**To Reproduce**
1. Start a Cyclops instance by following [this](https://cyclops-ui.com/docs/installation/install/manifest)
2. Hit `Add module`
3. Select `demo-template` template and create a Module with any values
4. You should be redirected to a page that shows all resources created for that Module, and you should see the issue with colors described above in the `Resources` section.

**Expected behavior**
Upper corners should be the same as the bottom corners

### PR DESCRIPTION
**Pull request by AKHIL-DyC**
closes #269 

## ✅ Checks
- [ ✅] I have updated the documentation as required
- [✅ ] I have performed a self-review of my code

### CODE REVIEW

**Comment by AKHIL-DyC** [comment]
@petar-cvit

File: cyclops-ui/src/components/pages/ModuleDetails.tsx [hunk 1]
```diff
@@ -471,12 +471,15 @@ const ModuleDetails = () => {
...
     }
-
     resourceCollapses.push(
       <Collapse.Panel
         header={genExtra(resource, resource.status)}
         key={collapseKey}
-        style={{ backgroundColor: getCollapseColor(collapseKey) }}
+        style={{
+          backgroundColor: getCollapseColor(collapseKey),
+          borderTopLeftRadius: resourceCollapses.length == 0 ? "7px" : "0px",
```
Comment (petar-cvit) [inline cyclops-ui/src/components/pages/ModuleDetails.tsx:480]: Why are you checking resourceCollapses.length == 0? Shouldn't it always be 7px? Also, why 7?

Comment (AKHIL-DyC) [reply cyclops-ui/src/components/pages/ModuleDetails.tsx:480]: i am checking that because 
240517_00h17m31s_screenshot
and 7 because it fitted

**Comment by AKHIL-DyC** [comment]
@petar-cvit

**Comment by AKHIL-DyC** [comment]
this

**Comment by AKHIL-DyC** [comment]
240517_00h20m57s_screenshot-min
@petar-cvit

**Comment by petar-cvit** [comment]
Oh okay, I get it. Good job. Can you add `index` to the start of that forEach (line 383.) and use that to check if it's the first collapse panel?

**Comment by AKHIL-DyC** [comment]
> Oh okay, I get it. Good job. Can you add `index` to the start of that forEach (line 383.) and use that to check if it's the first collapse panel?

sure ,made changes

File: cyclops-ui/src/components/pages/ModuleDetails.tsx [hunk 2]
```diff
@@ -471,12 +471,15 @@ const ModuleDetails = () => {
...
-
     resourceCollapses.push(
       <Collapse.Panel
         header={genExtra(resource, resource.status)}
         key={collapseKey}
-        style={{ backgroundColor: getCollapseColor(collapseKey) }}
+        style={{
+          backgroundColor: getCollapseColor(collapseKey),
+          borderTopLeftRadius: index == 0 ? "7px" : "0px",
+          borderTopRightRadius: index == 0 ? "7px" : "7px",
```
Comment (petar-cvit) [inline cyclops-ui/src/components/pages/ModuleDetails.tsx:481]: Can you update to "7px" : "0px"?

**Review by petar-cvit — CHANGES_REQUESTED** [review]

File: cyclops-ui/src/components/pages/ModuleDetails.tsx (hunk 2 above)
Comment (AKHIL-DyC) [reply cyclops-ui/src/components/pages/ModuleDetails.tsx]: > Can you update to "7px" : "0px"?

done

**Review by petar-cvit — APPROVED** [review]
Thanks @AKHIL-DyC
