### PR TITLE
fix:(#373) added edit and delete in template header

### LINKED ISSUE #373: `Edit` and `Delete` in templates header
Add `Edit` and `Delete` descriptions in the header of the templates table.
Screenshot 2024-06-23 at 14 50 31

### PR DESCRIPTION
**Pull request by tanbirali**
closes #373 

## 📑 Description
Added the Edit and Delete at the template header

## ✅ Checks
- [ ] I have updated the documentation as required
- [x] I have performed a self-review of my code

### CODE REVIEW

File: cyclops-ui/src/components/pages/TemplateStore/TemplateStore.tsx [hunk 1]
```diff
@@ -211,22 +222,26 @@ const TemplateStore = () => {
...
-                      {
-                        [styles.success]: requestStatus[template.name] === "success",
-                        [styles.error]: requestStatus[template.name] === "error"
-                      }
-                    )}
+                    className={classNames(styles.statustemplate, {
+                      [styles.success]:
+                        requestStatus[template.name] === "success",
+                      [styles.error]: requestStatus[template.name] === "error",
+                    })}
```
Comment (petar-cvit) [inline cyclops-ui/src/components/pages/TemplateStore/TemplateStore.tsx:229]: Can you format it like this?

```suggestion
                    className={classNames(styles.statustemplate, {
                      [styles.success]: requestStatus[template.name] === "success",
                      [styles.error]: requestStatus[template.name] === "error",
                    })}
```

**Review by petar-cvit — CHANGES_REQUESTED** [review]

**Review by petar-cvit — APPROVED** [review]
Thanks @tanbirali! 🧡
